### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by funmolde** [craeckor/user-agent-scraper#1]
Hello , your two files are viruses
this is an endroid for developers and open source, not for sharing viruses to infect people😒.
 I'm going to report you 

ipchanger.exe
https://www.virustotal.com/gui/file/bcfd4de1b7b7e4f143b5fb8456732f4c9b1845a774463d8a2a9edc5ec0f5b566

file updater.exe
https://www.virustotal.com/gui/file/1c8039d46508d48ce5edc1c7137a022962053f0b05450c4fe87a7321d3bafbf6/details

**Comment by craeckor** [comment]
Go and look at the code by yourself if you think that this open-source project is a virus: https://github.com/seevik2580/tor-ip-changer
And it's literally mentioned in the README: https://github.com/craeckor/user-agent-scraper?tab=readme-ov-file#shout-out
Here, I added a disclaimer: https://github.com/craeckor/user-agent-scraper?tab=readme-ov-file#disclaimer
